"""Test-only backend double.

The shipped project is Foundry-only (no offline/demo backend).  For fast,
credential-free unit and integration tests we use this in-repo fake, which
returns deterministic, structurally-valid stub content so the full workflow can
run without any network calls.  It is **not** part of the ``trip_planner``
package and is never selectable at runtime.
"""

from __future__ import annotations

import textwrap
from typing import Optional

from trip_planner.backends.base import BackendAdapter


class FakeBackend(BackendAdapter):
    """Returns hardcoded illustrative content for every prompt (tests only)."""

    @property
    def name(self) -> str:
        return "fake"

    async def generate(
        self,
        system_prompt: str,
        user_message: str,
        *,
        max_tokens: int = 1024,
        agent_name: Optional[str] = None,
    ) -> str:
        return textwrap.dedent(
            """\
            [FAKE BACKEND — no external calls were made]

            This is a placeholder response generated by the test FakeBackend.
            In a real run (foundry or foundry_models backend) the language model
            would produce destination-specific content here.

            Attractions: Placeholder attraction A, Placeholder attraction B
            Weather: Mild and pleasant for the selected month.
            Events: Local festival, Cultural exhibition
            Cultural tips: Respect local customs, Carry local currency
            Day 1: Morning sightseeing (09:00-12:00), Lunch break (12:00-13:00), Afternoon museum (13:00-16:00)
            Day 2: Day trip to nearby landmark, Evening food market
            Day 3: Shopping district, Farewell dinner
            Flight estimate: $400, Hotel estimate: $450, Food estimate: $200, Activities: $150, Total: $1200
            """
        )
