"""Demo backend — returns deterministic template responses without any external calls.

This is the safe fallback used when:
  - ``TRIP_BACKEND=demo`` is set explicitly, or
  - the requested backend lacks the required credentials at startup.

It lets the full workflow run end-to-end so the structural demo can proceed
without any Azure or GitHub credentials.
"""

from __future__ import annotations

import textwrap

from trip_planner.backends.base import BackendAdapter


class DemoBackend(BackendAdapter):
    """Returns hardcoded illustrative content for every prompt."""

    @property
    def name(self) -> str:
        return "demo"

    async def generate(
        self,
        system_prompt: str,
        user_message: str,
        *,
        max_tokens: int = 1024,
    ) -> str:
        # Return a minimal but structurally valid stub so all agents produce
        # something parseable.  In a real run the LLM fills this in properly.
        return textwrap.dedent(
            """\
            [DEMO MODE — no external calls were made]

            This is a placeholder response generated by the DemoBackend.
            In a real run (github_models or foundry backend) the language model
            would produce destination-specific content here.

            Attractions: Placeholder attraction A, Placeholder attraction B
            Weather: Mild and pleasant for the selected month.
            Events: Local festival, Cultural exhibition
            Cultural tips: Respect local customs, Carry local currency
            Day 1: Morning sightseeing (09:00-12:00), Lunch break (12:00-13:00), Afternoon museum (13:00-16:00)
            Day 2: Day trip to nearby landmark, Evening food market
            Day 3: Shopping district, Farewell dinner
            Flight estimate: $400, Hotel estimate: $450, Food estimate: $200, Activities: $150, Total: $1200
            """
        )
